# BigQuery Dataset
resource "google_bigquery_dataset" "keyword_planner" {
  dataset_id                 = var.dataset_id
  location                   = var.region
  description                = "Dataset for SMART Engine data"
  delete_contents_on_destroy = false

  labels = {
    env        = "production"
    managed_by = "terraform"
  }

  lifecycle {
    ignore_changes = [default_table_expiration_ms, default_partition_expiration_ms]
  }
}

# Dataset Items Table (v3) — unified replacement for keyword_results + portfolio_items_v2
resource "google_bigquery_table" "dataset_items" {
  dataset_id          = google_bigquery_dataset.keyword_planner.dataset_id
  table_id            = "dataset_items"
  deletion_protection = false

  description = "Unified dataset items table for all dataset types (keywords, ad copy, search terms, text lists)"

  schema = jsonencode([
    {
      name        = "dataset_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Foreign key to datasets collection in Firestore"
    },
    {
      name        = "item_text"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "The text item (keyword, ad copy string, search term, etc.)"
    },
    {
      name        = "added_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Timestamp when this item was added"
    },
    {
      name        = "avg_monthly_searches"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Average monthly search volume (keyword-type datasets only)"
    },
    {
      name        = "competition"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Competition level: LOW, MEDIUM, HIGH (keyword-type datasets only)"
    },
    {
      name        = "competition_index"
      type        = "FLOAT"
      mode        = "NULLABLE"
      description = "Competition index 0-100 (keyword-type datasets only)"
    },
    {
      name        = "low_top_of_page_bid_usd"
      type        = "FLOAT"
      mode        = "NULLABLE"
      description = "Low top-of-page bid in USD (keyword-type datasets only)"
    },
    {
      name        = "high_top_of_page_bid_usd"
      type        = "FLOAT"
      mode        = "NULLABLE"
      description = "High top-of-page bid in USD (keyword-type datasets only)"
    },
    {
      name        = "source_url"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Source URL that seeded this item (google_ads_keywords type only)"
    }
  ])

  time_partitioning {
    type  = "DAY"
    field = "added_at"
  }

  clustering = ["dataset_id"]
}

# Dataset Embeddings Cache Table (v3) — replaces portfolio_embeddings_v2
resource "google_bigquery_table" "dataset_embeddings" {
  dataset_id          = google_bigquery_dataset.keyword_planner.dataset_id
  table_id            = "dataset_embeddings"
  deletion_protection = false

  description = "Cached intent strings and embeddings for all dataset types"

  schema = jsonencode([
    {
      name        = "dataset_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Foreign key to datasets collection in Firestore"
    },
    {
      name        = "item_text"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "The original item text"
    },
    {
      name        = "intent_string"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Normalized intent string generated by Gemini"
    },
    {
      name        = "embedding"
      type        = "FLOAT64"
      mode        = "REPEATED"
      description = "Text embedding vector (512 dimensions)"
    },
    {
      name        = "prompt_hash"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "SHA256 of the intent prompt used to generate this embedding"
    },
    {
      name        = "embedded_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Timestamp when this embedding was generated"
    }
  ])

  clustering = ["dataset_id", "prompt_hash"]
}

# Gap Analysis Results Table
resource "google_bigquery_table" "gap_analysis_results" {
  dataset_id          = google_bigquery_dataset.keyword_planner.dataset_id
  table_id            = "gap_analysis_results"
  deletion_protection = false

  description = "Semantic gap analysis results: source items ranked by distance from closest target item"

  schema = jsonencode([
    {
      name        = "analysis_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique identifier for the gap analysis run (UUID)"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Timestamp when the analysis was run"
    },
    {
      name        = "keyword_text"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "The source item text"
    },
    {
      name        = "keyword_intent"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Normalized intent string for the source item"
    },
    {
      name        = "closest_portfolio_item"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "The target item semantically closest to this source item"
    },
    {
      name        = "closest_portfolio_intent"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Intent string of the closest target item"
    },
    {
      name        = "semantic_distance"
      type        = "FLOAT64"
      mode        = "NULLABLE"
      description = "Cosine distance between source and closest target item (lower = more similar)"
    },
    {
      name        = "avg_monthly_searches"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Average monthly search volume (populated for keyword-type source datasets)"
    }
  ])

  time_partitioning {
    type  = "DAY"
    field = "created_at"
  }

  clustering = ["analysis_id"]
}

# Filter Results Table
resource "google_bigquery_table" "filter_results" {
  dataset_id          = google_bigquery_dataset.keyword_planner.dataset_id
  table_id            = "filter_results"
  deletion_protection = false

  description = "LLM-evaluated boolean filter results per keyword per filter execution"

  schema = jsonencode([
    {
      name        = "execution_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique identifier for the filter execution (UUID)"
    },
    {
      name        = "analysis_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Foreign key to gap_analysis_results"
    },
    {
      name        = "keyword_text"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "The keyword being evaluated"
    },
    {
      name        = "label"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Filter label (e.g. non_branded, purchase_intent) — snapshotted at execution time"
    },
    {
      name        = "result"
      type        = "BOOL"
      mode        = "NULLABLE"
      description = "LLM evaluation result (true = passes filter)"
    },
    {
      name        = "confidence"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "LLM confidence: high, medium, or low"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Timestamp when this filter result was generated"
    }
  ])

  time_partitioning {
    type  = "DAY"
    field = "created_at"
  }

  clustering = ["analysis_id", "label"]
}
